%% Andmeallikad

graph LR
    subgraph Andmeallikad
        A[Synthea andmestik] 
        B[SNOMED CT - ICD-10 maping]
        C[Meteostat API]
    end

    subgraph Toorkiht
        D[(PATIENT)]
        E[(ENCOUNTER)]
        F[(ORGANIZATION)]
        G[(SNOMED CT to ICD-10)]
        H[(WEATHER)]
        I[(CONDITION)]
    end

    A --> D
    A --> E
    A --> F
    A --> I
    
    B --> G

    C --> H