%% Andmevoo vooskeem

flowchart LR

    %% =========================
    %% ALGALLIKAD
    %% =========================
    A[Synthea terviseandmed]
    A1[patients]
    A2[conditions]
    A3[encounters]
    A4[organizations]

    B1[SNOMED CT - ICD-10 maping]

    C[Ilmavaatluse API]
   
    A --> A1
    A --> A2
    A --> A3
    A --> A4


    %% =========================
    %% TOORKIHT / PRONKS KIHT
    %% =========================
    D[TOORKIHT]

    A1 --> D
    A2 --> D
    A3 --> D
    A4 --> D
    B1 --> D
    C --> D

    D1[raw_patients]
    D2[raw_conditions]
    D3[raw_encounters]
    D4[raw_snomedct-icd10_maping]
    D5[raw_weather]
    D6[raw_regions]
    D7[raw_organizations]

    D --> D1
    D --> D2
    D --> D3
    D --> D4
    D --> D5
    D --> D6
    D --> D7

    %% =========================
    %% PUHASTUSKIHT / HÕBE KIHT
    %% =========================
    E[(PUHASTUSKIHT)]
    E1[dim_region]
    E2[dim_patients]
    E3[dim_diagnosis]
    E4[dim_date]
    %% faktitabel moodustub lausendist: ühel päeval esinenud ilm ühe piirkonna kohta
    E5[fact_weather_region_day] 
    %% faktitabel moodustub lausendist ühe patsiendi sümptomite algus ja lõpp ühe piirkonna kohta
    E6[fact_patient_weather_region]
    %% faktitabel moodustub lausendist ühe patsiendi sündmus ühes päevas
    E7[fact_patient_day]
    E8[dim_weather_type]

    D --> E
     
    E --> E1
    E --> E2
    E --> E3
    E --> E4 
    E --> E5
    E --> E6
    E --> E7
    E --> E8
       
    E--> F

    %% =========================
    %% ÄRIKIHT / KULD KIHT
    %% =========================
    F[(ÄRIKIHT)]

    F --> H

    %% =========================
    %% ANDMEKVALITEET
    %% =========================
    G[Andmekvaliteedi testid]
    G1[not null]
    G2[unique]
    G3[väärtuste vahemik]
    G4[referentsseosed]
    G5[duplikaatide kontroll]

    G --> F 
    G1 --> G
    G2 --> G
    G3 --> G
    G4 --> G
    G5 --> G

    %% =========================
    %% ANALÜÜTIKA / VISUAALID
    %% =========================
    H[ANALÜÜTIKA]
    H1[Valuga seotud haigussündmuste arv Massachusettsi ja California piirkondades]
    H2[Valuga seotud haigustega patsientide arv ilmastikutüübi järgi]
    H3[Korduvate valuga seotud diagnooside osakaal kombinatsioonis ilmastikutüübi ja rõhulangusega piirkonna lõikes]

    H --> H1
    H --> H2
    H --> H3