-- Create a separate database for Airflow's internal metadata (DAG runs, task state).
-- This keeps Airflow's tables isolated from the ETL warehouse tables.
CREATE DATABASE airflow_db;

-- Create the three-layer warehouse schemas:
--   raw     → data lands here as-is from source systems
--   staging → dbt cleans and standardises raw data
--   marts   → final analytical models consumed by Superset
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts;

-- ── raw schema tables ─────────────────────────────────────────────────────────
-- Creation order follows FK dependencies:
--   patients, organizations → encounters → conditions
--   organizations → organization_locations

-- Patients generated by Synthea (FHIR Patient resource).
CREATE TABLE IF NOT EXISTS raw.patients (
    id        TEXT PRIMARY KEY,  -- Synthea FHIR resource ID
    state     TEXT,              -- Two-letter state code, e.g. "MA"
    loaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Healthcare organisations (hospitals, clinics) from Synthea (FHIR Organization resource).
-- Must be created before raw.encounters (which has an FK to this table).
CREATE TABLE IF NOT EXISTS raw.organizations (
    id        TEXT PRIMARY KEY,  -- Synthea FHIR resource ID
    city      TEXT,
    state     TEXT,
    lat       DOUBLE PRECISION,  -- From FHIR Location resource in hospitalInformation bundle
    lon       DOUBLE PRECISION,
    loaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Healthcare encounters (visits) from Synthea (FHIR Encounter resource).
CREATE TABLE IF NOT EXISTS raw.encounters (
    encounter_id    TEXT PRIMARY KEY,
    patient_id      TEXT NOT NULL REFERENCES raw.patients(id),
    reason_code     TEXT,        -- SNOMED code for the reason
    reason_display  TEXT,        -- Human-readable reason
    organization_id TEXT REFERENCES raw.organizations(id),
    loaded_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Diagnoses recorded during encounters (FHIR Condition resource).
-- encounter_id is nullable because some conditions are not tied to a specific visit.
CREATE TABLE IF NOT EXISTS raw.conditions (
    condition_id          TEXT PRIMARY KEY,
    patient_id            TEXT NOT NULL REFERENCES raw.patients(id),
    encounter_id          TEXT REFERENCES raw.encounters(encounter_id),  -- Nullable FK
    clinical_status       TEXT,        -- e.g. "active", "resolved"
    category_code         TEXT,        -- e.g. "encounter-diagnosis"
    condition_code        TEXT,        -- SNOMED code
    condition_code_system TEXT,        -- Coding system URI
    condition_display     TEXT,        -- Human-readable condition name
    onset_datetime        TIMESTAMPTZ,
    abatement_datetime    TIMESTAMPTZ, -- When the condition ended (NULL if ongoing)
    loaded_at             TIMESTAMPTZ DEFAULT NOW()
);

-- Daily weather observations fetched via the Open-Meteo archive API.
-- Rows are keyed by location (lat/lon) and date; duplicates are rejected by the UNIQUE constraint.
CREATE TABLE IF NOT EXISTS raw.weather (
    id        BIGSERIAL PRIMARY KEY,
    lat       DOUBLE PRECISION NOT NULL,
    lon       DOUBLE PRECISION NOT NULL,
    date      DATE NOT NULL,
    tavg      DOUBLE PRECISION,  -- Average temperature (°C)
    tmin      DOUBLE PRECISION,  -- Minimum temperature (°C)
    tmax      DOUBLE PRECISION,  -- Maximum temperature (°C)
    prcp      DOUBLE PRECISION,  -- Precipitation (mm)
    pres      DOUBLE PRECISION,  -- Air pressure (hPa)
    loaded_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (lat, lon, date)      -- Prevent duplicate rows for the same location and day
);

-- ICD-10 to SNOMED mapping loaded from ingestion/icd_snomed.csv.
-- Used by dbt to map condition SNOMED codes to ICD-10 codes.
CREATE TABLE IF NOT EXISTS raw.icd10_codes (
    icd10_code     TEXT NOT NULL,
    description_et TEXT,              -- Haiguse nimetus eesti keeles
    snomed_code    TEXT NOT NULL,
    loaded_at      TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (icd10_code, snomed_code)  -- M16 has two SNOMED codes → two rows
);
