-- Create a separate database for Airflow's internal metadata (DAG runs, task state).
-- This keeps Airflow's tables isolated from the ETL warehouse tables.
CREATE DATABASE airflow_db;

-- Create the three-layer warehouse schemas:
--   raw     → data lands here as-is from source systems
--   staging → dbt cleans and standardises raw data
--   marts   → final analytical models consumed by Superset
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts;

-- ── raw schema tables ─────────────────────────────────────────────────────────

-- Patients generated by Synthea (FHIR Patient resource).
-- lat/lon are used by fetch_weather.py to look up weather at the patient's location.
CREATE TABLE IF NOT EXISTS raw.patients (
    id                TEXT PRIMARY KEY,  -- Synthea FHIR resource ID
    birthdate         DATE,
    gender            TEXT,
    city              TEXT,
    state             TEXT,
    lat               DOUBLE PRECISION,  -- Geographic coordinates for weather lookup
    lon               DOUBLE PRECISION,
    deceased_datetime TIMESTAMPTZ,       -- NULL if patient is still alive
    loaded_at         TIMESTAMPTZ DEFAULT NOW()
);

-- Healthcare encounters (visits) from Synthea (FHIR Encounter resource).
-- Each encounter belongs to one patient and may have one reason.
CREATE TABLE IF NOT EXISTS raw.encounters (
    encounter_id             TEXT PRIMARY KEY,
    status                   TEXT,        -- e.g. "finished"
    class_code               TEXT,        -- e.g. "AMB" (ambulatory), "IMP" (inpatient)
    type_code                TEXT,        -- SNOMED or CPT procedure code
    type_display             TEXT,        -- Human-readable type label
    patient_id               TEXT NOT NULL REFERENCES raw.patients(id),
    period_start             TIMESTAMPTZ,
    period_end               TIMESTAMPTZ,
    practitioner_display     TEXT,
    location_display         TEXT,
    service_provider_display TEXT,
    reason_code              TEXT,        -- SNOMED code for the reason
    reason_display           TEXT,        -- Human-readable reason
    loaded_at                TIMESTAMPTZ DEFAULT NOW()
);

-- Diagnoses recorded during encounters (FHIR Condition resource).
-- encounter_id is nullable because some conditions are not tied to a specific visit.
-- Synthea generates SNOMED CT codes only. ICD-10 mapping requires a separate mapping table (e.g. NLM SNOMED-to-ICD-10) joined on condition_code.
CREATE TABLE IF NOT EXISTS raw.conditions (
    condition_id          TEXT PRIMARY KEY,
    patient_id            TEXT NOT NULL REFERENCES raw.patients(id),
    encounter_id          TEXT REFERENCES raw.encounters(encounter_id),  -- Nullable FK
    clinical_status       TEXT,        -- e.g. "active", "resolved"
    verification_status   TEXT,        -- e.g. "confirmed"
    category_code         TEXT,        -- e.g. "encounter-diagnosis"
    condition_code        TEXT,        -- SNOMED or ICD-10 code
    condition_code_system TEXT,        -- Coding system URI
    condition_display     TEXT,        -- Human-readable condition name
    onset_datetime        TIMESTAMPTZ,
    recorded_date         DATE,
    abatement_datetime    TIMESTAMPTZ, -- When the condition ended (NULL if ongoing)
    loaded_at             TIMESTAMPTZ DEFAULT NOW()
);

-- Daily weather observations fetched via the Meteostat Python library.
-- Rows are keyed by location (lat/lon) and date; duplicates are rejected by the UNIQUE constraint.
CREATE TABLE IF NOT EXISTS raw.weather (
    id        BIGSERIAL PRIMARY KEY,
    lat       DOUBLE PRECISION NOT NULL,
    lon       DOUBLE PRECISION NOT NULL,
    date      DATE NOT NULL,
    tavg      DOUBLE PRECISION,  -- Average temperature (°C)
    tmin      DOUBLE PRECISION,  -- Minimum temperature (°C)
    tmax      DOUBLE PRECISION,  -- Maximum temperature (°C)
    prcp      DOUBLE PRECISION,  -- Precipitation (mm)
    pres      DOUBLE PRECISION,  -- Air pressure (hPa)
    loaded_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (lat, lon, date)      -- Prevent duplicate rows for the same location and day
);

-- WHO ICD-10 disease classification codes fetched from the WHO ICD API.
-- Used by dbt to enrich raw.conditions with standardised labels.
CREATE TABLE IF NOT EXISTS raw.icd_codes (
    code        TEXT PRIMARY KEY,  -- ICD-10 code (e.g. "E11")
    title       TEXT,              -- Short label (e.g. "Type 2 diabetes mellitus")
    description TEXT,              -- Longer description from WHO API
    parent_code TEXT,              -- Parent code for hierarchy traversal (e.g. "E11" → "E10-E14")
    loaded_at   TIMESTAMPTZ DEFAULT NOW()
);
